/**
 * Optional sidecar of programmatically-refreshed asset moves. When
 * present, individual `(event, asset, horizon)` triples in this file
 * override the hand-curated values in data/events.ts.
 *
 * Generated by `pnpm refresh-prices` from FRED + Stooq.
 *
 * Each event has a `source` map per asset ("fred" | "stooq" | "missing")
 * and an `asOf` map showing the trading day actually used for t. The UI
 * uses these to render a "FRED-verified" / "Stooq-verified" badge on
 * individual asset rows so readers can distinguish hand-curated
 * approximations from canonical numbers.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { Asset } from "./refresh/sources";

export type AssetMoveProvenance = "fred" | "stooq" | "missing" | "approximate";

interface EventOverride {
  date: string;
  asOf: Record<string, string | null>;
  source: Record<string, "fred" | "stooq" | "missing">;
  series: Record<string, Partial<Record<"d1" | "d5" | "m1" | "m3" | "m6", number>>>;
}

interface SidecarShape {
  generatedAt: string;
  generatorVersion: string;
  events: Record<string, EventOverride>;
}

let _cached: SidecarShape | null | undefined;

function getSidecar(): SidecarShape | null {
  if (_cached !== undefined) return _cached;
  const path = join(process.cwd(), "data", "asset-moves.json");
  if (!existsSync(path)) {
    _cached = null;
    return null;
  }
  try {
    _cached = JSON.parse(readFileSync(path, "utf8")) as SidecarShape;
    return _cached;
  } catch (err) {
    console.warn("[asset-moves-sidecar] failed to load:", err);
    _cached = null;
    return null;
  }
}

/**
 * Apply sidecar overrides on top of hand-curated values per event. For
 * each (asset, horizon) the sidecar value wins when present; otherwise
 * the hand-curated value is preserved. Returns:
 *   - the merged ReturnSeries
 *   - per-asset provenance: "fred" | "stooq" | "approximate"
 *   - per-asset asOf for canonical values
 */
export function applyAssetMovesSidecar<T extends { id: string; assetMoves: Record<Asset, Record<string, number | null>> }>(
  event: T,
): {
  assetMoves: T["assetMoves"];
  provenance: Record<Asset, AssetMoveProvenance>;
  asOf: Record<Asset, string | null>;
} {
  const sidecar = getSidecar();
  const override = sidecar?.events[event.id];

  const provenance: Record<Asset, AssetMoveProvenance> = {
    sp500: "approximate",
    ust10y: "approximate",
    dxy: "approximate",
    gold: "approximate",
    oil: "approximate",
    creditHY: "approximate",
    vix: "approximate",
  };
  const asOf: Record<Asset, string | null> = {
    sp500: null,
    ust10y: null,
    dxy: null,
    gold: null,
    oil: null,
    creditHY: null,
    vix: null,
  };
  if (!override) {
    return { assetMoves: event.assetMoves, provenance, asOf };
  }

  // Deep-clone the assetMoves so we don't mutate the curated source.
  const merged: Record<Asset, Record<string, number | null>> = {
    sp500: { ...event.assetMoves.sp500 },
    ust10y: { ...event.assetMoves.ust10y },
    dxy: { ...event.assetMoves.dxy },
    gold: { ...event.assetMoves.gold },
    oil: { ...event.assetMoves.oil },
    creditHY: { ...event.assetMoves.creditHY },
    vix: { ...event.assetMoves.vix },
  };

  for (const asset of Object.keys(merged) as Asset[]) {
    const overrideSeries = override.series[asset];
    const overrideSource = override.source[asset];
    if (overrideSource && overrideSource !== "missing") {
      provenance[asset] = overrideSource;
      asOf[asset] = override.asOf[asset] ?? null;
    }
    if (overrideSeries) {
      for (const [k, v] of Object.entries(overrideSeries)) {
        if (typeof v === "number") {
          merged[asset][k] = v;
        }
      }
    }
  }

  return { assetMoves: merged as T["assetMoves"], provenance, asOf };
}
