/**
 * Optional sidecar of conformal-calibrated quantiles. Generated by
 * `pnpm conformal` and read at runtime by the brief UI to render
 * calibrated 80% intervals alongside the empirical N=3 ranges.
 *
 * When the sidecar is absent, the UI falls back to empirical-only
 * presentation with the existing "empirical range over N=3, not
 * calibrated" disclaimer.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { ConformalTable } from "./conformal";

interface SidecarShape {
  corpusVersion: string;
  alpha: number;
  kNN: number;
  generatedAt: string;
  table: ConformalTable;
}

let _cached: SidecarShape | null | undefined;

export function getConformalSidecar(): SidecarShape | null {
  if (_cached !== undefined) return _cached;
  const path = join(process.cwd(), "data", "conformal-quantiles.json");
  if (!existsSync(path)) {
    _cached = null;
    return null;
  }
  try {
    _cached = JSON.parse(readFileSync(path, "utf8")) as SidecarShape;
    return _cached;
  } catch (err) {
    console.warn("[conformal-sidecar] load failed:", err);
    _cached = null;
    return null;
  }
}
