/**
 * Optional build-time sidecar of corpus embeddings, used when a Postgres
 * is not configured. Generated by `pnpm embeddings --json` into
 * data/embeddings.json. The file is gitignored by default; check it in
 * for production deployments without a DB.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

interface SidecarShape {
  model: string;
  dimensions: number;
  generatedAt: string;
  embeddings: Record<string, number[]>;
}

let _sidecar: Map<string, number[]> | null | undefined;

export function getEmbeddingsSidecar(): Map<string, number[]> | null {
  if (_sidecar !== undefined) return _sidecar;

  const path = join(process.cwd(), "data", "embeddings.json");
  if (!existsSync(path)) {
    _sidecar = null;
    return null;
  }
  try {
    const raw = readFileSync(path, "utf8");
    const parsed = JSON.parse(raw) as SidecarShape;
    _sidecar = new Map(Object.entries(parsed.embeddings));
    return _sidecar;
  } catch (err) {
    console.warn("[embeddings-sidecar] failed to load:", err);
    _sidecar = null;
    return null;
  }
}
