/**
 * Optional build-time sidecar for the corpus regime centroids. Mirrors
 * embeddings-sidecar.ts: when no Postgres is available, the matching
 * code reads from data/regime-centroids.json (generated by
 * `pnpm regime:centroids --json`).
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

interface SidecarShape {
  version: string;
  dimensions: string[];
  generatedAt: string;
  centroids: Record<
    string,
    { raw: Array<number | null>; z: Array<number | null>; coverage: number }
  >;
}

let _cached: SidecarShape | null | undefined;

export function getRegimeCentroidsSidecar(): SidecarShape | null {
  if (_cached !== undefined) return _cached;
  const path = join(process.cwd(), "data", "regime-centroids.json");
  if (!existsSync(path)) {
    _cached = null;
    return null;
  }
  try {
    _cached = JSON.parse(readFileSync(path, "utf8")) as SidecarShape;
    return _cached;
  } catch (err) {
    console.warn("[regime-centroids-sidecar] failed to load:", err);
    _cached = null;
    return null;
  }
}
